version: "3.9"
services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: minhasenha
      MYSQL_DATABASE: order
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-pminhasenha"]
      interval: 5s
      timeout: 5s
      retries: 20

  shipping:
    build: ./shipping
    environment:
      ENV: development
      SHIPPING_PORT: "50052"
    ports:
      - "50052:50052"
    depends_on:
      - mysql

  order:
    build: ./order
    environment:
      ENV: development
      APPLICATION_PORT: "3000"
      DATA_SOURCE_URL: root:minhasenha@tcp(mysql:3306)/order?parseTime=true
      SHIPPING_ADDR: shipping:50052
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
      shipping:
        condition: service_started
