apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: order
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: order
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: order
    spec:
      containers:
        - env:
            - name: APPLICATION_PORT
              value: "3000"
            - name: DATA_SOURCE_URL
              value: root:minhasenha@tcp(mysql:3306)/order?parseTime=true
            - name: ENV
              value: development
            - name: SHIPPING_ADDR
              value: shipping:50052
            - name: PAYMENT_SERVICE_URL
              value: http://payment:50051  
          image: microservicesfinal-order
          name: order
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
      
