apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_USER: bXlzcWw=      # "mysql" base64
  MYSQL_PASSWORD: bWluaGFzZW5oYQ==  # "minhasenha" base64
  MYSQL_ROOT_PASSWORD: cm9vdA==  # "root" base64